const settings = {
  gravity:      { value: 0.32,  min: 0.05, max: 1.0,  step: 0.01, label: 'Gravity' },
  jumpForce:    { value: 6.5,   min: 1.0,  max: 15.0, step: 0.1,  label: 'Jump Height' },
  walkSpeed:    { value: 1.8,   min: 0.5,  max: 6.0,  step: 0.1,  label: 'Walk Speed' },
  runMult:      { value: 1.6,   min: 1.0,  max: 5.0,  step: 0.1,  label: 'Run Multiplier' },
  jumpYOffset:  { value: -2,    min: -30,  max: 30,   step: 1,    label: 'Jump Y Offset' },
  runYOffset:   { value: 0.2,   min: -30,  max: 30,   step: 0.1,  label: 'Run Y Offset' },
  animSpeed:    { value: 7,     min: 1,    max: 20,   step: 1,    label: 'Anim Speed' },
  boltDur:      { value: 101,   min: 0,    max: 120,  step: 1,    label: 'Bolt Duration' },
  flashDur:     { value: 1,     min: 0,    max: 60,   step: 1,    label: 'Flash Duration' },
  flashDelay:   { value: 0,     min: 0,    max: 60,   step: 1,    label: 'Bolt→Flash Delay' },
  lightningFreq:{ value: 350,   min: 100,  max: 1200, step: 50,   label: 'Lightning Freq' },
  carryOffset:      { value: 9,     min: -30,  max: 20,   step: 1,    label: 'Carry Y Offset' },
  blueCarryOffset:  { value: 3,     min: -30,  max: 20,   step: 1,    label: 'Blue Carry Y' },
  carryOffsetL: { value: -6,    min: -40,  max: 40,   step: 1,    label: 'Carry X Left' },
  carryOffsetR: { value: 5,     min: -40,  max: 40,   step: 1,    label: 'Carry X Right' },
  carryJumpYL:  { value: -9,    min: -40,  max: 40,   step: 1,    label: 'Carry Jump Y (left)' },
  carryJumpYR:  { value: -9,    min: -40,  max: 40,   step: 1,    label: 'Carry Jump Y (right)' },
  carryJumpXL:  { value: -1,    min: -40,  max: 40,   step: 1,    label: 'Carry Jump X (left)' },
  carryJumpXR:  { value: -7,    min: -40,  max: 40,   step: 1,    label: 'Carry Jump X (right)' },
  flippedGndY:      { value: 7,    min: -20,  max: 20,   step: 1,   label: 'Flip Ground Y' },
  blueFlippedGndY:  { value: 5,    min: -20,  max: 20,   step: 1,   label: 'Blue Flip Y' },
  blueGpBounce:     { value: 0,    min: 0,    max: 20,   step: 0.5, label: 'Blue GP Bounce' },
  gpBounce:         { value: 1.5,  min: 0,    max: 20,   step: 0.5, label: 'GP Bounce' },
  dashYOffset:  { value: 0,     min: -30,  max: 30,   step: 1,    label: 'Dash Y Offset' },
  throwStrength:{ value: 2.5,   min: 1,    max: 20,   step: 0.5,  label: 'Throw Strength' },
  redBounceBack:{ value: 4,     min: 0,    max: 20,   step: 0.5,  label: 'Axo Knockback' },
  redFlipGrav:  { value: 0.49,  min: 0.01, max: 2.0,  step: 0.01, label: 'Red Flip Grav' },
  homingHover:  { value: 12,    min: 0,    max: 60,   step: 1,    label: 'Homing Hover' },
  stunFrames:   { value: 100,   min: 0,    max: 300,  step: 10,   label: 'Spike Stun Dur' },
  furyFlashSpeed:{ value: 6,    min: 1,    max: 30,   step: 1,    label: 'Fury Flash Speed' },
  furySpeedMult: { value: 1.6,  min: 1.0,  max: 4.0,  step: 0.1,  label: 'Fury Speed Mult' },
  furyDuration:  { value: 960,  min: 60,   max: 3600, step: 60,   label: 'Fury Duration' },
  furyKillFill:  { value: 3,    min: 1,    max: 20,   step: 1,    label: 'Fury Kill Fill' },
  shadesXL:      { value: 9,    min: -30,  max: 30,   step: 1,    label: 'Shades X (left)' },
  shadesYL:      { value: 19,   min: 0,    max: 60,   step: 1,    label: 'Shades Y (left)' },
  shadesXR:      { value: 9,    min: -30,  max: 30,   step: 1,    label: 'Shades X (right)' },
  shadesYR:      { value: 19,   min: 0,    max: 60,   step: 1,    label: 'Shades Y (right)' },
  shadesJumpXL:  { value: 9,    min: -30,  max: 30,   step: 1,    label: 'Shades Jump X (left)' },
  shadesJumpYL:  { value: 22,   min: 0,    max: 60,   step: 1,    label: 'Shades Jump Y (left)' },
  shadesJumpXR:  { value: 9,    min: -30,  max: 30,   step: 1,    label: 'Shades Jump X (right)' },
  shadesJumpYR:  { value: 22,   min: 0,    max: 60,   step: 1,    label: 'Shades Jump Y (right)' },
  shadesSwimXL:  { value: 9,    min: -30,  max: 30,   step: 1,    label: 'Shades Swim X (left)' },
  shadesSwimYL:  { value: 24,   min: 0,    max: 60,   step: 1,    label: 'Shades Swim Y (left)' },
  shadesSwimXR:  { value: 9,    min: -30,  max: 30,   step: 1,    label: 'Shades Swim X (right)' },
  shadesSwimYR:  { value: 24,   min: 0,    max: 60,   step: 1,    label: 'Shades Swim Y (right)' },
};

// S.gravity instead of settings.gravity.value
const S = new Proxy(settings, { get: (t, k) => t[k].value });
